remote_theme: cotes2020/jekyll-theme-chirpy
title: Supply Chain Optimization
tagline: Automotive Supply Chain Analysis
description: Comprehensive supply chain optimization project for automotive manufacturing
url: 'https://akashbhargav12.github.io'
github:
  username: akashbhargav12
social:
  name: Akash Bhargav
  links:
    - https://akashbhargav12.github.io/Data-Portfolio/
    - https://www.linkedin.com/in/akash-bhargav/
